<#--import {RequestMapping} from "fengwuxp_common_fetch/src/annotations/mapping/RequestMapping";-->
import {PostMapping} from "fengwuxp_common_fetch/src/annotations/mapping/PostMapping";
import {GetMapping} from "fengwuxp_common_fetch/src/annotations/mapping/GetMapping";
import {DeleteMapping} from "fengwuxp_common_fetch/src/annotations/mapping/DeleteMapping";
import {PutMapping} from "fengwuxp_common_fetch/src/annotations/mapping/PutMapping";
import {PatchMapping} from "fengwuxp_common_fetch/src/annotations/mapping/PatchMapping";
import {FetchOptions} from "fengwuxp_common_fetch/src/FetchOptions";
import {Feign} from "fengwuxp_common_fetch/src/annotations/Feign";
import {RequestMethod} from "fengwuxp_common_fetch/src/constant/RequestMethod";
import {Signature} from "fengwuxp_common_fetch/src/annotations/security/Signature";
import {MediaType} from "fengwuxp_common_fetch/src/constant/http/MediaType";